# semtools Metadata (Initial Draft)
embeddings:
  primary: finance-embedding-model-v1
  secondary: general-embedding-model-v2
routing:
  rejection_threshold: 0.35
  human_escalation_threshold: 0.15
  update_schedule: nightly
  audit_log: data/processed/semtools-routing-log.csv
metadata_fields:
  - cost_estimate
  - latency_budget_ms
  - provenance_required
  - freshness_ts
  - compliance_tags
initial_tools:
  - name: market-data.pricing.get_ohlcv
    description: Retrieve verified OHLCV bars from exchange-approved providers.
    cost_estimate: medium
    latency_budget_ms: 500
    provenance_required: true
    compliance_tags: ["reg_scid", "MiFID"]
  - name: feature-engineering.compute_factor
    description: Compute momentum/volatility/mean reversion factors from price series.
    cost_estimate: low
    latency_budget_ms: 800
    provenance_required: true
    compliance_tags: ["model_validation"]
  - name: strategy.eval.run_backtest
    description: Trigger QuantConnect Lean Docker backtest run.
    cost_estimate: high
    latency_budget_ms: 3600000
    provenance_required: true
    compliance_tags: ["model_validation"]
  - name: risk.limits.evaluate_portfolio
    description: Evaluate portfolio exposures against VaR/CVaR and concentration limits.
    cost_estimate: medium
    latency_budget_ms: 2000
    provenance_required: true
    compliance_tags: ["risk", "reg_scid"]
  - name: compliance.generate_summary
    description: Produce compliance evidence summary for regulatory controls.
    cost_estimate: low
    latency_budget_ms: 1500
    provenance_required: true
    compliance_tags: ["compliance", "reporting"]
  - name: research.feed.list_insights
    description: Retrieve curated external research insights tagged by Innovation Scout.
    cost_estimate: low
    latency_budget_ms: 500
    provenance_required: true
    compliance_tags: ["innovation"]
  - name: strategy.validation.run_robustness
    description: Execute cross-validation, walk-forward, and bootstrap diagnostics on strategy returns.
    cost_estimate: medium
    latency_budget_ms: 1500
    provenance_required: true
    compliance_tags: ["model_validation", "risk"]
  - name: visualization.render_price_series
    description: Render annotated price/signal charts for human review and documentation.
    cost_estimate: medium
    latency_budget_ms: 2000
    provenance_required: true
    compliance_tags: ["visualization", "ux"]
  - name: quantconnect.project.sync
    description: Sync local strategy files to a QuantConnect cloud project via MCP (stub until server vendored).
    cost_estimate: medium
    latency_budget_ms: 3000
    provenance_required: true
    compliance_tags: ["quantconnect", "deployment"]
  - name: quantconnect.backtest.run
    description: Trigger QuantConnect cloud backtest for a project (stub until server vendored).
    cost_estimate: high
    latency_budget_ms: 600000
    provenance_required: true
    compliance_tags: ["quantconnect", "model_validation"]
  - name: quantconnect.backtest.status
    description: Poll QuantConnect cloud backtest status and retrieve statistics (stub until server vendored).
    cost_estimate: low
    latency_budget_ms: 2000
    provenance_required: true
    compliance_tags: ["quantconnect", "model_validation"]
  - name: semtools.parse
    description: Parse documents using semtools CLI (LlamaIndex semtools).
    cost_estimate: medium
    latency_budget_ms: 5000
    provenance_required: true
    compliance_tags: ["document_intelligence"]
  - name: semtools.search
    description: Semantic fuzzy search via semtools CLI.
    cost_estimate: medium
    latency_budget_ms: 2000
    provenance_required: true
    compliance_tags: ["document_intelligence"]
  - name: strategy.regime.detect_states
    description: Hidden Markov Model regime detection (requires hmmlearn).
    cost_estimate: high
    latency_budget_ms: 5000
    provenance_required: true
    compliance_tags: ["mathematical_model", "regime_detection"]
